# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20180604_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Availability',
        ),
        migrations.AddField(
            model_name='availability',
            name='Availability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.User'),
        ),
    ]
