# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20180606_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='UserTypeID',
        ),
        migrations.AddField(
            model_name='user',
            name='UserTypeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.UserType'),
        ),
    ]
