# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20180606_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.User'),
        ),
    ]
