# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_subjects_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectName', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='User',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.AddField(
            model_name='subject',
            name='Subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.SubjectTable'),
        ),
        migrations.AddField(
            model_name='subject',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.User'),
        ),
    ]
