# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20180614_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='User',
        ),
        migrations.AddField(
            model_name='subject',
            name='SubjectName',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='SubjectTable',
        ),
        migrations.AddField(
            model_name='subject_user',
            name='Subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Subject'),
        ),
        migrations.AddField(
            model_name='subject_user',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.User'),
        ),
    ]
