# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_auto_20180614_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start', models.DateTimeField()),
                ('End', models.DateTimeField()),
                ('Status', models.CharField(max_length=200)),
                ('Instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor', to='homepage.User')),
                ('Student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='homepage.User')),
                ('Subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Subject')),
            ],
        ),
        migrations.DeleteModel(
            name='SessionStatus',
        ),
    ]
